[project]
name = "omegat-ticket1565-segment-uniqid-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inquirer>=3.4.1",
    "tabulate>=0.9.0",
]
